[default]

    LEVEL_NAME = "DEBUG"

[development]

    [development.logs]
        LEVEL_NAME = "DEBUG"
        FORMAT = '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s - %(message)s'
    
    [development.i18n]
        default_locale = "ru"
        locales = ["ru", "en"]

    [development.bot]
        PARSE_MODE = 'HTML'

    [development.postgres]
        NAME = '11TT'
        HOST = '91.98.71.11'
        PORT = 5432
        USER = 'postgres'
    
    [development.redis]
        HOST = '91.98.71.11'
        PORT = 6379
        DATABASE = 1

    [development.nats]
        SERVERS = 'nats://91.98.71.11:4222'
        DELAYED_CONSUMER_SUBJECT = 'aiogram.delayed.messages'
        DELAYED_CONSUMER_STREAM = 'delayed_messages_aiogram'
        DELAYED_CONSUMER_DURABLE_NAME = 'delayed_messages_consumer'
    
    [development.cache]
        USE_CACHE = false